### PR TITLE
Move to using defaultDeserializeToVersion instead

### PR DESCRIPTION
**Pull request by brentryan**

### CODE REVIEW

**Comment by jonpeterson** [comment]
Going to go ahead and merge this into the branch and write tests for the new functionality, but it looks good.  Thanks.

**Comment by brentryan** [comment]
These bugs happened when I was testing deserialization of data that was missing the "modelVersion" property and then I wanted to serialize out that same object and I wanted it to match.  So basically the "modelVersion" would take the default value I set of 0 because it was missing, but when I serialize it out I didn't want it to serialize "modelVersion=0" because the calling api might not be able to accept it.

When I did this, the code didn't see field level annotations, only class level annotations.  Specifically I believe I was looking for 

```
    @JsonSerializeToVersion(defaultToSource = true)
    private String serializeToVersion;
```

Looking at the code it makes sense why this was missed... It was only looking for "serializeToVersionProperty.getAccessor()".

Let me know when you think you might be able to cut a new release for these changes.  I'd like to start cutting some releases of things internally that are starting to depend on this functionality now.

Thanks!

**Comment by jonpeterson** [comment]
I believe the reason you were seeing this issue was because your example is a `private` field.  Fields show up as accessors when one of the follow is true:
1. are `public`
2. the class has an auto-detect modifier (ex. `@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY))
3. the object mapper has been configured with the auto-detection settings
4. the field has a property annotation (ex. `@JsonProperty`)

Can you give what is currently in the `cvent-enhancements` branch a try after adjusting the field with one of the strategies?  I have removed the field-based lookup you added because I don't want to diverge from the standard Jackson property lookup strategy.  If you need to mask out the `modelVersion` when it is `0`, then I would think that should be something added to your model-specific `toPast` `VersionedModelConverter`.

Open to thoughts on this.

I will cut a release tonight if this is in a state that meets your needs.

**Comment by brentryan** [comment]
Odd...  We seem to have a bunch of code with only annotations like this on private fields with default ObjectMapper...

```
@JsonProperty("aProp")
private String foo;
```

It seems to work fine but maybe it's not even looking at the annotations and just looking at the field names... I'd have to verify.  Somehow it's all working.

I'll give a try and let you know.

**Comment by jonpeterson** [comment]
Right.  I'm saying that the following should work equivalently:

Getter/Setter

``` java
private String serializeToVersion;

@JsonSerializeToVersion(defaultToSource = true)
public String getSerializeToVersion() {
    return serializeToVersion;
}

@JsonSerializeToVersion(defaultToSource = true)
public void setSerializeToVersion() {
    return serializeToVersion;
}
```

Public Field

``` java
@JsonSerializeToVersion(defaultToSource = true)
public String serializeToVersion;
```

Private Field w/ @JsonProperty

``` java
@JsonProperty
@JsonSerializeToVersion(defaultToSource = true)
private String serializeToVersion;
```

**Comment by jonpeterson** [comment]
I cut a release (1.2.0).  Should show up in maven central within an hour or so.  Let me know if you have any issues.

**Comment by brentryan** [comment]
I re-tested with 1.2.0 and it appears like things are still broken for my use cases.  It looks like several of my changes aren't in 1.2.0.  I can't remember which of them was related to the annotation field stuff or not.

I'll see if I can re-create another PR based on 1.2.0 to show you the changes I still need for this to work.

`
{"field":"sample","guid":"d4456bb7-ac42-4115-813d-ce340fb5b2e4","test":null,"aBigOne":44,"aInt":44,"subcar":{"doors":false,"model":"toyota:tacoma","year":2009,"used":true},"model":"foo:bar","year":0,"new":"true","modelVersion":"1"}
`

This is just a hacky blob of JSON I'm testing with.  I'd expect to be able to deserialize this JSON into my java class object called Car.java and then serialize it back out and it should match exactly.

My Car.java class looks like this:

```
package com.cvent.versiontester;


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.github.jonpeterson.jackson.module.versioning.JsonSerializeToVersion;
import com.github.jonpeterson.jackson.module.versioning.JsonVersionedModel;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
//import javax.validation.Valid;
//import javax.validation.constraints.DecimalMax;
//import javax.validation.constraints.DecimalMin;

/**
 *
 * @author bryan
 */
@JsonVersionedModel(currentVersion = "3",
        toCurrentConverterClass = ToCurrentCarConverter.class,
        toPastConverterClass = ToPastCarConverter.class,
        defaultDeserializeToVersion = "0")
public class Car extends ParentCar {

    @JsonProperty
    @JsonSerializeToVersion(defaultToSource = true)
    private String serializeToVersion;

//    private DateTime dt;
//    private LocalDate ld;
//
//    public DateTime getDt() {
//        return dt;
//    }
//
//    public void setDt(DateTime dt) {
//        this.dt = dt;
//    }
//
//    public LocalDate getLd() {
//        return ld;
//    }
//
//    public void setLd(LocalDate ld) {
//        this.ld = ld;
//    }

    private UUID guid = UUID.randomUUID();

    /**
     * Get the value of guid
     *
     * @return the value of guid
     */
    public UUID getGuid() {
        return guid;
    }

    /**
     * Set the value of guid
     *
     * @param guid new value of guid
     */
    public void setGuid(UUID guid) {
        this.guid = guid;
    }

//    @Valid
    private ChildCar test;

    /**
     * Get the value of test
     *
     * @return the value of test
     */
    public ChildCar getTest() {
        return test;
    }

//    @DecimalMax("44.0")
    private BigDecimal aBigOne = new BigDecimal("44");

    /**
     * Get the value of aBigOne
     *
     * @return the value of aBigOne
     */
    public BigDecimal getaBigOne() {
        return aBigOne;
    }

    /**
     * Set the value of aBigOne
     *
     * @param aBigOne new value of aBigOne
     */
    public void setaBigOne(BigDecimal aBigOne) {
        this.aBigOne = aBigOne;
    }

//    @DecimalMin("5.0")
    private int aInt = 44;

    /**
     * Get the value of aInt
     *
     * @return the value of aInt
     */
    public int getaInt() {
        return aInt;
    }

    /**
     * Set the value of aInt
     *
     * @param aInt new value of aInt
     */
    public void setaInt(int aInt) {
        this.aInt = aInt;
    }

    /**
     * Set the value of test
     *
     * @param test new value of test
     */
    public void setTest(ChildCar test) {
        this.test = test;
    }

    private String make;

    public String getSerializeToVersion() {
        return serializeToVersion;
    }

    public void setSerializeToVersion(String serializeToVersion) {
        this.serializeToVersion = serializeToVersion;
    }

    private ChildCar subcar;

    /**
     * Get the value of subcar
     *
     * @return the value of subcar
     */
    public ChildCar getSubcar() {
        return subcar;
    }

    /**
     * Set the value of subcar
     *
     * @param subcar new value of subcar
     */
    public void setSubcar(ChildCar subcar) {
        this.subcar = subcar;
    }

    /**
     * Get the value of make
     *
     * @return the value of make
     */
    public String getMake() {
        return make;
    }

    /**
     * Set the value of make
     *
     * @param make new value of make
     */
    public void setMake(String make) {
        this.make = make;
    }

    private String model;

    /**
     * Get the value of model
     *
     * @return the value of model
     */
    public String getModel() {
        return model;
    }

    /**
     * Set the value of model
     *
     * @param model new value of model
     */
    public void setModel(String model) {
        this.model = model;
    }

    private int year;

    /**
     * Get the value of year
     *
     * @return the value of year
     */
    public int getYear() {
        return year;
    }

    /**
     * Set the value of year
     *
     * @param year new value of year
     */
    public void setYear(int year) {
        this.year = year;
    }

    private boolean used;

    /**
     * Get the value of used
     *
     * @return the value of used
     */
    public boolean isUsed() {
        return used;
    }

    /**
     * Set the value of used
     *
     * @param used new value of used
     */
    public void setUsed(boolean used) {
        this.used = used;
    }

    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
`
```

**Comment by brentryan** [comment]
FWIW, None of this works either without the field annotations changes.

```
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
public class Car extends ParentCar {

    @JsonProperty
    @JsonSerializeToVersion(defaultToSource = true)
    public String serializeToVersion;

```

**Pull request merged**
